/**
 * icmp.h
 * Useful ICMP definitions, because I couldn't find a header for Windows.
 *
 */

#pragma once
#include <Windows.h>
#include "socket.h"

// types
#define ICMP_ECHO_REPLY 0
#define ICMP_DESTINATION_UNREACHABLE 3
#define ICMP_SOURCE_QUENCH 4 // DEPRECATED
#define ICMP_REDIRECT 5
#define ICMP_ALTERNATE_HOST_ADDRESS 6 // DEPRECATED
#define ICMP_ECHO_REQUEST 8
#define ICMP_ROUTER_ADVERTISEMENT 9
#define ICMP_ROUTER_SELECTION 10
#define ICMP_TIME_EXCEEDED 11
#define ICMP_PARAM_PROBLEM 12
#define ICMP_TIMESTAMP 13
#define ICMP_TIMESTAMP_REPLY 14
#define ICMP_INFO_REQUEST 15 // DEPRECATED
#define ICMP_INFO_REPLY 16 // DEPRECATED
#define ICMP_ADDRESS_MASK_REQUEST 17 // DEPRECATED
#define ICMP_ADDRESS_MASK_REPLY 18 // DEPRECATED
#define ICMP_TRACEROUTE 30 // DEPRECATED
#define ICMP_DATAGRAM_CONVERSION_ERROR 31 // DEPRECATED
#define ICMP_MOBILE_HOST_REDIRECT 32 // DEPRECATED
#define ICMP_IPV6_WHERE_ARE_YOU 33 // DEPRECATED
#define ICMP_IPV6_I_AM_HERE 34 // DEPRECATED
#define ICMP_IPV6_REQUEST ICMP_IPV6_WHERE_ARE_YOU
#define ICMP_IPV6_REPLY ICMP_IPV6_I_AM_HERE
#define ICMP_MOBILE_REGISTRATION_REQUEST 35 // DEPRECATED
#define ICMP_MODILE_REGISTRATION_REPLY 36 // DEPRECATED
#define ICMP_DOMAIN_NAME_REQUEST 37 // DEPRECATED
#define ICMP_DOMAIN_NAME_REPLY 38 // DEPRECATED
#define ICMP_SKIP 39 // DEPRECATED
#define ICMP_PHOTURIS 40
#define ICMP_EXTENDED_ECHO_REQUEST 42
#define ICMP_EXTENDED_ECHO_REPLY 43

typedef struct ICMP_HEADER
{
	BYTE type;
	BYTE code;
	WORD checksum;
	union
	{
		struct echo
		{
			WORD id;
			WORD sequence;
		};
	};
} ICMP_HEADER, *PICMP_HEADER;

WORD IcmpChecksum(PBYTE *data, DWORD dataSize);
BOOL IcmpSendEchoRequest(SOCKET socket, PBYTE data, DWORD dataSize);